In [3]:
#import libraries 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

loading all the csv files

In [5]:
city_day = pd.read_csv(r"D:\personal_project\aqi-predictor\data\raw\city_day.csv")

In [6]:
city_day.head(5)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [7]:
city_day.info()

<class 'pandas.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  str
 1   Date        29531 non-null  str
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  str
dtypes: float64(13), str(3)
memory usage: 3.6 MB

In [8]:
city_day['Date']=pd.to_datetime(city_day['Date'], format='%Y-%m-%d')

In [9]:
city_day.shape

(29531, 16)

In [10]:
city_day.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [11]:
city_day['City'].unique()

<StringArray>
[         'Ahmedabad',             'Aizawl',          'Amaravati',
           'Amritsar',          'Bengaluru',             'Bhopal',
       'Brajrajnagar',         'Chandigarh',            'Chennai',
         'Coimbatore',              'Delhi',          'Ernakulam',
           'Gurugram',           'Guwahati',          'Hyderabad',
             'Jaipur',         'Jorapokhar',              'Kochi',
            'Kolkata',            'Lucknow',             'Mumbai',
              'Patna',           'Shillong',            'Talcher',
 'Thiruvananthapuram',      'Visakhapatnam']
Length: 26, dtype: str

In [12]:
city_day.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [13]:
city_day.describe()

,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
count,29531,24933.000000,18391.000000,25949.000000,25946.000000,25346.000000,19203.000000,27472.000000,25677.000000,25509.000000,23908.000000,21490.000000,11422.000000,24850.000000
mean,2018-05-14 05:40:15.807118,67.450578,118.127103,17.574730,28.560659,32.309123,23.483476,2.248598,14.531977,34.491430,3.280840,8.700972,3.070128,166.463581
min,2015-01-01 00:00:00,0.040000,0.010000,0.020000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000
25%,2017-04-16 00:00:00,28.820000,56.255000,5.630000,11.750000,12.820000,8.580000,0.510000,5.670000,18.860000,0.120000,0.600000,0.140000,81.000000
50%,2018-08-05 00:00:00,48.570000,95.680000,9.890000,21.690000,23.520000,15.850000,0.890000,9.160000,30.840000,1.070000,2.970000,0.980000,118.000000
75%,2019-09-03 00:00:00,80.590000,149.745000,19.950000,37.620000,40.127500,30.020000,1.450000,15.220000,45.570000,3.080000,9.150000,3.350000,208.000000
max,2020-07-01 00:00:00,949.990000,1000.000000,390.680000,362.210000,467.630000,352.890000,175.810000,193.860000,257.730000,455.030000,454.850000,170.370000,2049.000000
std,NaN,64.661449,90.605110,22.785846,24.474746,31.646011,25.684275,6.962884,18.133775,21.694928,15.811136,19.969164,6.323247,140.696585

In [14]:
city_day=city_day.sort_values(['City','Date'],ascending=[True,True]).reset_index(drop=True)

In [15]:
city_day.columns

Index(['City', 'Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2',
       'O3', 'Benzene', 'Toluene', 'Xylene', 'AQI', 'AQI_Bucket'],
      dtype='str')

In [16]:
col_to_fill=['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','Benzene','Toluene','Xylene']
city_day[col_to_fill]=(city_day.groupby('City')[col_to_fill].transform(lambda x:x.interpolate(method='linear',limit=5,limit_direction='forward')))

In [17]:
missing_valus=city_day.groupby('City')[col_to_fill].apply(lambda x:x.isnull().sum())
print (missing_valus)
print(city_day[col_to_fill].isnull().mean()*100)

                    PM2.5  PM10    NO   NO2   NOx   NH3   CO   SO2    O3  \
City
Ahmedabad             588  1594   575   575   561  2009  575   597   596
Aizawl                  0     0     0     0     0     0    0     0     0
Amaravati              36    36    36    36    36    36   55    38    36
Amritsar               82    17    53     8   267     4   19    86    55
Bengaluru             101   327     0     0     0   133    0     0    81
Bhopal                  4     4     4     4     4     4    4     4     4
Brajrajnagar          111   105   138   134   103   136   85    97   106
Chandigarh              9     0     0     0     0     1    0     0     0
Chennai                99  1688    18    18    18   420    8    18    21
Coimbatore              0     0    48     1     0    46    0     0     0
Delhi                   0    55     0     0     0     0    0    99    76
Ernakulam               0     0     0    41     0     0    0     0   162
Gurugram               83   891    53    54   370  1560   42    67    38
Guwahati                0     0     1     1     1     1    1     1     1
Hyderabad             100   330    14    14     0   336    0    14    14
Jaipur                  5     5     5     5   112     5    5     5     5
Jorapokhar            768   126   112   112  1169   254  344   186   147
Kochi                   0     0     0     1     0    11    0     0     0
Kolkata                38    38    14    13     1     0    0    45    32
Lucknow                86  2009     8     8   270   999    8    20     8
Mumbai               1215  1231  1202  1229   465  1614    6  1185  1160
Patna                 290  1667   168   168   168  1667   38   169   233
Shillong               42    45    41    41    21    41   21    41    41
Talcher               112   102   132   138   101   107   79   114    84
Thiruvananthapuram      6     6     6     6     2   104    2     6     6
Visakhapatnam         177   181   177   204     6   168    6   177   180

                    Benzene  Toluene  Xylene
City
Ahmedabad               432      432     432
Aizawl                    2        2     113
Amaravati                45       45      87
Amritsar                135      153     154
Bengaluru               154       24    2009
Bhopal                  289      289     289
Brajrajnagar            117      938     938
Chandigarh                0        0       0
Chennai                 155      120    2009
Coimbatore                0        0     386
Delhi                     0        0     756
Ernakulam                 0        0       0
Gurugram                421      593    1560
Guwahati                  1      502     502
Hyderabad               109      109     109
Jaipur                    5        5    1114
Jorapokhar             1169     1169    1169
Kochi                   162        0     162
Kolkata                   1        1     416
Lucknow                  55       69    2009
Mumbai                  182      968     970
Patna                    49       51      51
Shillong                 21       22     310
Talcher                 187      729     925
Thiruvananthapuram     1112     1112    1112
Visakhapatnam             6        6       6
PM2.5      13.382547
PM10       35.410247
NO          9.498493
NO2         9.518811
NOx        12.444550
NH3        32.697843
CO          4.395381
SO2        10.053842
O3         10.450036
Benzene    16.284582
Toluene    24.851851
Xylene     59.557753
dtype: float64

In [18]:
city_day.isnull().sum()

City              0
Date              0
PM2.5          3952
PM10          10457
NO             2805
NO2            2811
NOx            3675
NH3            9656
CO             1298
SO2            2969
O3             3086
Benzene        4809
Toluene        7339
Xylene        17588
AQI            4681
AQI_Bucket     4681
dtype: int64

In [19]:
city_day.drop(columns=['Xylene'], inplace=True)

In [20]:
city_day['Month'] = city_day['Date'].dt.month
feature_cols=['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','Benzene','Toluene']
city_day[feature_cols] = city_day.groupby(['City', 'Month'])[feature_cols].transform(
    lambda x: x.fillna(x.mean()) )

In [21]:
city_day.isnull().sum()

City             0
Date             0
PM2.5           94
PM10          2619
NO               0
NO2             31
NOx           1169
NH3           3564
CO               0
SO2              0
O3             162
Benzene       2733
Toluene       4300
AQI           4681
AQI_Bucket    4681
Month            0
dtype: int64

In [22]:
city_day = city_day.dropna(subset=['AQI'])

In [23]:
city_day.shape

(24850, 16)

In [24]:
print(city_day[feature_cols + ['AQI']].isnull().sum())
print((city_day[feature_cols + ['AQI']].isnull().mean() * 100).round(2))

PM2.5        52
PM10       2338
NO            0
NO2          31
NOx         771
NH3        2586
CO            0
SO2           0
O3          153
Benzene    2260
Toluene    3512
AQI           0
dtype: int64
PM2.5       0.21
PM10        9.41
NO          0.00
NO2         0.12
NOx         3.10
NH3        10.41
CO          0.00
SO2         0.00
O3          0.62
Benzene     9.09
Toluene    14.13
AQI         0.00
dtype: float64

In [25]:
core_cols = ['PM2.5', 'PM10', 'NO2', 'NOx', 'NH3', 'O3']  # NO, CO, SO2 already 0% missing

city_day[core_cols] = city_day.groupby('City')[core_cols].transform(
    lambda x: x.fillna(x.mean())
)
city_day.drop(columns=['Benzene', 'Toluene'], inplace=True)

In [26]:
print(city_day.isnull().sum())

City             0
Date             0
PM2.5            0
PM10          1893
NO               0
NO2              0
NOx            771
NH3           1334
CO               0
SO2              0
O3             153
AQI              0
AQI_Bucket       0
Month            0
dtype: int64

In [27]:
print(city_day[city_day['PM10'].isnull()]['City'].unique())
print(city_day[city_day['NH3'].isnull()]['City'].unique())

<StringArray>
['Lucknow']
Length: 1, dtype: str
<StringArray>
['Ahmedabad']
Length: 1, dtype: str

In [28]:
print(city_day[['PM2.5', 'PM10', 'NO2', 'AQI']].describe())

              PM2.5          PM10           NO2           AQI
count  24850.000000  22957.000000  24850.000000  24850.000000
mean      67.008496    117.384772     28.784832    166.463581
std       62.653628     83.746521     24.569178    140.696585
min        0.040000      0.030000      0.010000     13.000000
25%       28.892500     58.810000     11.852500     81.000000
50%       48.545000     99.466000     21.930000    118.000000
75%       80.517500    148.327634     37.967500    208.000000
max      914.940000    917.080000    362.210000   2049.000000

In [29]:
city_day.dropna(inplace=True)

In [30]:
# Check how many rows exceed the valid CPCB AQI range
print((city_day['AQI'] > 500).sum())
print(city_day[city_day['AQI'] > 500]['City'].unique())

109
<StringArray>
['Amritsar', 'Delhi', 'Gurugram', 'Guwahati', 'Hyderabad', 'Patna', 'Talcher']
Length: 7, dtype: str

In [31]:
city_day = city_day[city_day['AQI'] <= 500]

print(city_day.shape)
print(city_day['City'].nunique())
print(city_day.isnull().sum())

(20590, 14)
22
City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
AQI           0
AQI_Bucket    0
Month         0
dtype: int64

In [32]:
print(city_day[['PM2.5', 'PM10', 'NO2', 'AQI']].describe())

              PM2.5          PM10           NO2           AQI
count  20590.000000  20590.000000  20590.000000  20590.000000
mean      61.999085    115.320508     27.052917    141.878679
std       56.330996     81.931261     21.068910     94.721606
min        0.040000      0.030000      0.010000     13.000000
25%       27.092500     57.002500     12.140000     77.000000
50%       45.585000     96.055000     21.440000    109.000000
75%       74.450000    150.147500     36.257500    172.000000
max      868.660000    847.410000    362.210000    500.000000

In [33]:
city_day.shape

(20590, 14)

In [34]:
# Date range per city, post-cleaning
print(city_day.groupby('City')['Date'].agg(['min', 'max', 'count']))

                          min        max  count
City
Aizawl             2020-03-12 2020-07-01    111
Amaravati          2017-11-25 2020-07-01    841
Amritsar           2017-02-28 2020-07-01   1122
Bengaluru          2015-03-21 2020-07-01   1910
Bhopal             2019-09-18 2020-07-01    278
Brajrajnagar       2017-12-08 2020-06-12    713
Chandigarh         2019-09-03 2020-07-01    299
Chennai            2015-03-24 2020-07-01   1884
Coimbatore         2019-06-13 2020-06-30    344
Delhi              2015-01-01 2020-07-01   1951
Gurugram           2016-01-23 2020-07-01   1431
Guwahati           2019-02-17 2020-07-01    493
Hyderabad          2015-03-31 2020-07-01   1876
Jaipur             2017-06-20 2020-07-01   1094
Kochi              2020-01-23 2020-07-01    158
Kolkata            2018-04-11 2020-07-01    754
Mumbai             2018-05-07 2020-07-01    775
Patna              2015-10-03 2020-07-01   1434
Shillong           2019-08-28 2020-07-01    205
Talcher            2018-02-08 2020-07-01    694
Thiruvananthapuram 2017-06-23 2020-07-01   1052
Visakhapatnam      2016-07-07 2020-07-01   1171

In [35]:
city_day = city_day[~city_day['City'].isin(['Aizawl', 'Kochi'])]
print(city_day.shape)
print(city_day['City'].nunique())

(20321, 14)
20

feature engineering

In [36]:
city_day.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,AQI,AQI_Bucket,Month
2123,Amaravati,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,184.0,Moderate,11
2124,Amaravati,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,197.0,Moderate,11
2125,Amaravati,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,198.0,Moderate,11
2126,Amaravati,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,188.0,Moderate,11
2127,Amaravati,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,173.0,Moderate,11

In [37]:
city_day = city_day.sort_values(['City', 'Date']).reset_index(drop=True)

city_day.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,AQI,AQI_Bucket,Month
0,Amaravati,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,184.0,Moderate,11
1,Amaravati,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,197.0,Moderate,11
2,Amaravati,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,198.0,Moderate,11
3,Amaravati,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,188.0,Moderate,11
4,Amaravati,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,173.0,Moderate,11

In [38]:
city_day['AQI_lag1'] = city_day.groupby('City')['AQI'].shift(1)   # yesterday's AQI
city_day['AQI_lag2'] = city_day.groupby('City')['AQI'].shift(2)   # 2 days ago
city_day['AQI_lag3'] = city_day.groupby('City')['AQI'].shift(3)   # 3 days ago
city_day['AQI_lag7'] = city_day.groupby('City')['AQI'].shift(7)   # same day last week

In [39]:
city_day['AQI_roll3'] = city_day.groupby('City')['AQI'].transform(lambda x: x.shift(1).rolling(3).mean())
city_day['AQI_roll7'] = city_day.groupby('City')['AQI'].transform(lambda x: x.shift(1).rolling(7).mean())

city_day = city_day.dropna()
print(city_day.shape)

(20181, 20)

In [40]:
city_day['Month'] = city_day['Date'].dt.month
city_day['DayOfWeek'] = city_day['Date'].dt.dayofweek
city_day['Year'] = city_day['Date'].dt.year

# Optional but valuable: season, since Indian pollution is strongly seasonal
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Summer'
    elif month in [6, 7, 8, 9]:
        return 'Monsoon'
    else:
        return 'Post-Monsoon'

city_day['Season'] = city_day['Month'].apply(get_season)

In [41]:
original_columns = city_day['City'].unique()
original_columns

<StringArray>
[         'Amaravati',           'Amritsar',          'Bengaluru',
             'Bhopal',       'Brajrajnagar',         'Chandigarh',
            'Chennai',         'Coimbatore',              'Delhi',
           'Gurugram',           'Guwahati',          'Hyderabad',
             'Jaipur',            'Kolkata',             'Mumbai',
              'Patna',           'Shillong',            'Talcher',
 'Thiruvananthapuram',      'Visakhapatnam']
Length: 20, dtype: str

In [43]:
import pickle

with open("../models/original_city.pkl", "wb") as file:
    pickle.dump(original_columns, file)

In [44]:
city_day = pd.get_dummies(city_day, columns=['City', 'Season'], drop_first=False)

In [45]:
print(city_day.columns)

Index(['Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3',
       'AQI', 'AQI_Bucket', 'Month', 'AQI_lag1', 'AQI_lag2', 'AQI_lag3',
       'AQI_lag7', 'AQI_roll3', 'AQI_roll7', 'DayOfWeek', 'Year',
       'City_Amaravati', 'City_Amritsar', 'City_Bengaluru', 'City_Bhopal',
       'City_Brajrajnagar', 'City_Chandigarh', 'City_Chennai',
       'City_Coimbatore', 'City_Delhi', 'City_Gurugram', 'City_Guwahati',
       'City_Hyderabad', 'City_Jaipur', 'City_Kolkata', 'City_Mumbai',
       'City_Patna', 'City_Shillong', 'City_Talcher',
       'City_Thiruvananthapuram', 'City_Visakhapatnam', 'Season_Monsoon',
       'Season_Post-Monsoon', 'Season_Summer', 'Season_Winter'],
      dtype='str')

In [46]:

city_day.to_csv('../data/processed/city_day_features.csv', index=False)

In [47]:
city_day.to_pickle('../data/processed/city_day_features.pkl')

In [48]:
original_columns

<StringArray>
[         'Amaravati',           'Amritsar',          'Bengaluru',
             'Bhopal',       'Brajrajnagar',         'Chandigarh',
            'Chennai',         'Coimbatore',              'Delhi',
           'Gurugram',           'Guwahati',          'Hyderabad',
             'Jaipur',            'Kolkata',             'Mumbai',
              'Patna',           'Shillong',            'Talcher',
 'Thiruvananthapuram',      'Visakhapatnam']
Length: 20, dtype: str